#include "fundamental_functions/game_functions_draughts.h"
#include "fundamental_functions/interface_jeu_dames.h"
#include "new_rafle/new_rafle.h"
#include "new_rafle/new_rafle_test.h"
#include "time.h"